### ISSUE TITLE
Error with launching panes

### ISSUE THREAD

**Issue by JustinTBrown** [briangonzalez/termrc#9]
I get the following error pretty much no matter what I do:

```
** Starting termrc using: 'Termfile'
** Please wait until all panes have fully launched!
/var/folders/pg/ysvh9jzx24l5sngg468mxpsc0000gn/T/termrc.osascript20141122-7730-1g16dvy:911:915: execution error: iTerm got an error: Can’t get terminal 2. Invalid index. (-1719)
```

I've reduced my Termfile to the simplest possible configuration just in case that was the issue:

```yml
root:
  ~/Documents/Code/feedback-app

commands:
  rails_c:	rails c	# Rails Console

layout:
  - [ rails_c ]	        # 1 pane
```

Ideas?
